parameters:
    pim_versioning.update_guesser.attribute_group.class:   Pim\Bundle\VersioningBundle\UpdateGuesser\AttributeGroupUpdateGuesser
    pim_versioning.update_guesser.attribute_option.class:  Pim\Bundle\VersioningBundle\UpdateGuesser\AttributeOptionUpdateGuesser
    pim_versioning.update_guesser.chained.class:           Pim\Bundle\VersioningBundle\UpdateGuesser\ChainedUpdateGuesser
    pim_versioning.update_guesser.contains_products.class: Pim\Bundle\VersioningBundle\UpdateGuesser\ContainsProductsUpdateGuesser
    pim_versioning.update_guesser.association.class:       Pim\Bundle\VersioningBundle\UpdateGuesser\AssociationUpdateGuesser
    pim_versioning.update_guesser.translations.class:      Pim\Bundle\VersioningBundle\UpdateGuesser\TranslationsUpdateGuesser
    pim_versioning.update_guesser.versionable.class:       Pim\Bundle\VersioningBundle\UpdateGuesser\VersionableUpdateGuesser
    pim_versioning.update_guesser.associations.class:      Pim\Bundle\VersioningBundle\UpdateGuesser\AssociationsUpdateGuesser

services:
    pim_versioning.update_guesser.attribute_group:
        class: '%pim_versioning.update_guesser.attribute_group.class%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.attribute_option:
        class: '%pim_versioning.update_guesser.attribute_option.class%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.contains_products:
        class: '%pim_versioning.update_guesser.contains_products.class%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.association:
        class: '%pim_versioning.update_guesser.association.class%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.translations:
        class: '%pim_versioning.update_guesser.translations.class%'
        arguments:
            - '%pim_versioning.versionable_entities%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.versionable:
        class: '%pim_versioning.update_guesser.versionable.class%'
        arguments:
            - '%pim_versioning.versionable_entities%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.associations:
        class: '%pim_versioning.update_guesser.associations.class%'
        arguments:
            - '%pim_versioning.versionable_entities%'
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.family_attribute_requirement:
        class: Pim\Bundle\VersioningBundle\UpdateGuesser\FamilyAttributeRequirementUpdateGuesser
        tags:
            - { name: pim_versioning.update_guesser }

    pim_versioning.update_guesser.chained:
        class: '%pim_versioning.update_guesser.chained.class%'
