parameters:
    pim_ui.controller.ajax_option.class: Akeneo\Platform\Bundle\UIBundle\Controller\AjaxOptionController

services:
    pim_ui.controller.ajax_option:
        class: '%pim_ui.controller.ajax_option.class%'
        arguments:
            - '@doctrine'
            - '@pim_reference_data.registry'

    pim_enrich.controller.rest.form_extension:
        class: 'Akeneo\Platform\Bundle\UIBundle\Controller\InternalApi\FormExtensionController'
        arguments:
            - '@pim_enrich.provider.form_extension'
