parameters:
    pim_enrich.encoder.json.class:     Symfony\Component\Serializer\Encoder\JsonEncoder

services:
    pim_enrich.encoder.json:
        public: false
        class: '%pim_enrich.encoder.json.class%'
        tags:
            - { name: pim_internal_api_serializer.encoder, priority: 90 }
