services:
    pim_enrichment.massive_import.command.constraint.existing_category:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ExistingCategoriesValidator'
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_existing_categories }
