services:
    pim_enrichment.massive_import.command.constraint.existing_category:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ExistingCategoriesValidator'
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_existing_categories }

    pim_enrichment.massive_import.command.constraint.existing_attributes_in_values:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ExistingAttributesInValuesValidator'
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_existing_attributes }

    pim_enrichment.massive_import.command.constraint.existing_locales_in_values:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ExistingLocalesInValuesValidator'
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_existing_locales }

    pim_enrichment.massive_import.command.constraint.existing_channels_in_values:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ExistingChannelsInValuesValidator'
        arguments:
            - '@database_connection'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_existing_channels }

    pim_enrichment.massive_import.command.constraint.product_value_collection:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\ProductValueCollectionValidator'
        arguments:
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_validate_product_value_collection }

    pim_enrichment.massive_import.command.constraint.text_value_validator:
        class: 'Akeneo\Pim\Enrichment\Bundle\MassiveImport\Validation\Constraints\TextValueValidator'
        arguments:
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: validator.constraint_validator, alias: batch_api_validate_text_value }
